### ISSUE TITLE
Sample ProviderConfig to use direclty.

### ISSUE THREAD

**Issue by luebken** [crossplane-contrib/provider-tf-aws#111]
### What problem are you facing?
When I'm installing the providerconfig I keep running into the problem of using the wrong APIVersion:` apiVersion: aws.crossplane.io/v1beta1` instead of a`piVersion: aws.tf.crossplane.io/v1alpha1`

### How could Crossplane help solve your problem?
Provide a sample providerconfig similar to https://raw.githubusercontent.com/crossplane/crossplane/release-1.4/docs/snippets/configure/aws/providerconfig.yaml

**Comment by turkenh** [comment]
@luebken indeed we already have an example here: https://github.com/crossplane-contrib/provider-tf-aws/blob/main/examples/tfaws/providerconfig.yaml 
Just in case you're not aware.

**Comment by luebken** [comment]
I was not. Perfect thanks.

**Comment by luebken** [comment]
Actually, I was looking for a ProviderConfig with without the Secret so I can use it directly with `kubectl apply -f URL`

**Comment by haarchri** [comment]
is this still relevant ?
so we can simply add the following manifest like classic provider-aws

```
---
apiVersion: aws.jet.crossplane.io/v1alpha1
kind: ProviderConfig
metadata:
  name: example
spec:
  credentials:
    source: None
```

**Comment by apmartins85** [comment]
trying to help ..
controllerConfig
```
piVersion: pkg.crossplane.io/v1alpha1
kind: ControllerConfig
metadata:
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::accountId:role/crossplane-role
  name: terrajet-config
spec:
  podSecurityContext:
    fsGroup: 2000
 ```
provider
```
apiVersion: pkg.crossplane.io/v1
kind: Provider
metadata:
  annotations:
  name: provider-jet
spec:
  controllerConfigRef:
    name: terrajet-config
```

 providerConfig
 ```
 apiVersion: aws.jet.crossplane.io/v1alpha1
kind: ProviderConfig
metadata:
  name: provider-jet
spec:
  credentials:
    source: InjectedIdentity
   ```
